config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'
  resources :queries, only: [:index, :show]
  get '/', to: redirect('/auth/login')

  get '/auth/login'
  post '/auth/login'
  get '/auth/logout'

  post '/api/index'
end

app/models/application_record.rb
# frozen_string_literal: true

# base application record for all application
# generated by rails new .
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/query.rb
# frozen_string_literal: true

# the query saved in the database
class Query < ApplicationRecord
  belongs_to :request_log
  belongs_to :response_log
end

app/models/request_log.rb
# frozen_string_literal: true

# request object from query
class RequestLog < ApplicationRecord
end

app/models/response_log.rb
# frozen_string_literal: true

# response object from query
class ResponseLog < ApplicationRecord
end

app/models/user.rb
# frozen_string_literal: true

# a user that can use the application
class User < ApplicationRecord
  has_secure_password
  has_secure_password :recovery_password, validations: false
end

app/controllers/api_controller.rb
# frozen_string_literal: true

# POST /api/index to send an api
class ApiController < ApplicationController
  skip_before_action :verify_authenticity_token

  # rubocop:disable Metrics/AbcSize
  def index
    return render plain: 'Type is empty', status: :bad_request if params[:type].to_s.empty?
    return render plain: 'Content is empty', status: :bad_request if params[:content].to_s.empty?

    begin
      content = Base64.decode64(params[:content])
      type = params[:type]
    rescue StandardError
      return render plain: 'Content is not a valid base64', status: :bad_request
    end

    query = process_query(type, content)
    render json: query, status: :created
  end
  # rubocop:enable Metrics/AbcSize

  private

  def create_query
    now = DateTime.current
    query = Query.new
    query.key = now.to_s(:number)
    query.save
    query
  end

  def process_query(type, content)
    query = create_query
    query.request_log_id = create_request(request).id
    query.save

    response = call_external_api(type, content)
    query.response_log_id = create_response(response).id
    query.save

    query
  end

  # rubocop:disable Metrics/MethodLength
  def create_request(request)
    requestlog = RequestLog.new
    requestlog.fullpath = request.fullpath
    requestlog.method = request.method
    requestlog.query_parameters = request.query_parameters
    requestlog.ip = request.ip
    requestlog.remote_ip = request.remote_ip
    requestlog.body = request.body.string
    requestlog.content_length = request.content_length
    requestlog.raw_post = request.raw_post
    requestlog.save

    requestlog
  end
  # rubocop:enable Metrics/MethodLength

  def create_response(response)
    responselog = ResponseLog.new
    responselog.code = response.code
    responselog.body = response.body
    responselog.headers = response
    responselog.save

    responselog
  end

  # rubocop:disable Metrics/MethodLength
  def call_external_api(type, content)
    if type == 'test'
      url = 'https://test.com'
      method = Net::HTTP::Get
    elsif type == 'hosco'
      url = 'https://www.hosco.com'
      method = Net::HTTP::Post
    else
      url = 'https://www.google.com'
      method = Net::HTTP::Get
    end

    url = URI.parse(url)
    req = method.new(url)
    req.body = content
    Net::HTTP.start(url.host, url.port) do |http|
      http.request(req)
    end
  end
  # rubocop:enable Metrics/MethodLength
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# the basic controller for the whole application
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_current_user

  private

  def set_current_user
    logger.debug "Session user id #{session[:user_id]}"

    return unless session[:user_id]

    @current_user = User.find(session[:user_id])
    logger.debug "Current user #{@current_user}"
  end
end

app/controllers/auth_controller.rb
# frozen_string_literal: true

# manage the authentification
class AuthController < ApplicationController
  def login
    return unless request.post?

    user = User.where(email: params[:user][:email]).first

    if user&.authenticate(params[:user][:password])
      save_logged_user(user)
    else
      flash[:error] = "Nom d'utilisateur et/ou mot de passe incorrect"
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to root_url
    flash[:info] = 'Déconnexion'
  end

  private

  def save_logged_user(user)
    session[:user_id] = user.id
    flash[:info] = "Bienvenue #{user.email} !"
    redirect_to root_url
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# redirect the user if authenticated or not
class HomeController < ApplicationController
  def index
    if @current_user
      redirect_to queries_url
    else
      redirect_to auth_login_url
    end
  end
end

app/controllers/queries_controller.rb
# frozen_string_literal: true

# display all queries
class QueriesController < ApplicationController
  before_action :set_query, only: [:show]

  # GET /queries
  # GET /queries.json
  def index
    unless @current_user
      flash[:error] = 'Accès interdit'
      redirect_to root_url
      return
    end

    @queries = Query.order(created_at: :desc).page params[:page]
  end

  # GET /queries/1
  # GET /queries/1.json
  def show
    return if @current_user

    flash[:error] = 'Accès interdit'
    redirect_to root_url
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_query
    @query = Query.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def query_params
    params.fetch(:query, {})
  end
end

app/helpers/api_helper.rb
# frozen_string_literal: true

# defined by rails
module ApiHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# defined by rails
module ApplicationHelper
end

app/helpers/auth_helper.rb
# frozen_string_literal: true

# defined by rails
module AuthHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

# defined by rails
module HomeHelper
end

app/helpers/queries_helper.rb
# frozen_string_literal: true

# defined by rails
module QueriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Negotiator</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div style="position: absolute; top: 20px; right: 20px;">

    <% if flash[:info] %>
      <div class="toast" role="alert" aria-live="assertive" aria-atomic="true" data-delay="10000">
        <div class="toast-header">
          <span class="mr-auto badge badge-info"><i class="fas fa-info"></i></span>
          <small class="text-muted">maintenant</small>
          <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="toast-body">
          <%= flash[:info] %>
        </div>
      </div>
    <% end %>

    <% if flash[:error] %>
      <div class="toast" role="alert" aria-live="assertive" aria-atomic="true" data-delay="10000">
        <div class="toast-header">
          <span class="mr-auto badge badge-error"><i class="fas fa-exclamation"></i></span>
          <small class="text-muted">maintenant</small>
          <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="toast-body">
          <%= flash[:error] %>
        </div>
      </div>
    <% end %>
  </div>

  <%= yield %>
</body>

</html>

app/views/queries/index.html.erb
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-auto">
            <h1 class="text-center">
                <%= @current_user.email %> <a class="btn btn-secondary" href="/auth/logout" role="button" aria-pressed="true">Déconnexion</a>
            </h1>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <p id="notice"><%= notice %></p>

            <table class="table table-striped table-dark">
                <thead>
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">Key</th>
                    <th scope="col">Date de création</th>
                    <th scope="col">Date de mise à jour</th>
                    <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    <% @queries.each do |query| %>
                      <tr>
                        <th scope="row"><%= query.id %></th>
                        <td><%= query.key %></td>
                        <td><%= query.created_at %></td>
                        <td><%= query.updated_at %></td>
                        <td><%= link_to 'Voir', query, class: "btn btn-secondary" %></td>
                      </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>

    <div class="row justify-content-md-center">
        <div class="col-auto">
            <%= paginate @queries %>
        </div>
    </div>
</div>

app/views/queries/show.html.erb
<div class="container">
    <div class="row">
        <div class="col">
            <p id="notice"><%= notice %></p>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <h1 class="card-title"><%= @query.key %></h1>
                </div>
                <div class="card-body">
                    <h6 class="card-subtitle mb-2 text-muted"><span class="badge badge-secondary">id: <%= @query.id %></span> <%= @query.created_at %></h6>

                    <hr />

                    <h4>Request</h4>
                    <ul class="list-group">
                        <li class="list-group-item">
                            <span class="badge badge-secondary">fullpath</span>
                            <%= @query.request_log.fullpath %>
                        </li>
                        <li class="list-group-item">
                            <span class="badge badge-secondary">method</span>
                            <%= @query.request_log.method %>
                        </li>
                        <li class="list-group-item">
                            <span class="badge badge-secondary">query_parameters</span>
                            <%= @query.request_log.query_parameters %>
                        </li>
                        <li class="list-group-item">
                            <span class="badge badge-secondary">ip</span>
                            <%= @query.request_log.ip %>
                        </li>
                        <li class="list-group-item">
                            <span class="badge badge-secondary">remote_ip</span>
                            <%= @query.request_log.remote_ip %>
                        </li>
                        <li class="list-group-item">
                            <span class="badge badge-secondary">body</span>
                            <%= @query.request_log.body %>
                        </li>
                        <li class="list-group-item">
                            <span class="badge badge-secondary">content_length</span>
                            <%= @query.request_log.content_length %>
                        </li>
                        <li class="list-group-item">
                            <span class="badge badge-secondary">raw_post</span>
                            <%= @query.request_log.raw_post %>
                        </li>
                    </ul>

                    <hr />

                    <h4>Response</h4>
                    <ul class="list-group">
                        <li class="list-group-item">
                            <span class="badge badge-secondary">code</span>
                            <%= @query.response_log.code %>
                        </li>
                        <li class="list-group-item">
                            <span class="badge badge-secondary">body</span>
                            <pre><%= @query.response_log.body %></pre>
                        </li>
                        <li class="list-group-item">
                            <span class="badge badge-secondary">headers</span>
                            <pre><%= @query.response_log.headers %></pre>
                        </li>
                    </ul>


                </div>
                <div class="card-footer">
                    <%= link_to 'Retour', queries_path, class: "card-link" %>
                </div>
            </div>
        </div>
    </div>
</div>